services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: focusboard
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: ./focusboard-api
    env_file: ./focusboard-api/.env # DATABASE_URL=postgres://devashishSarmah@db:5432/focusboard
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  ui:
    build: ./focusboard-ui
    depends_on:
      - api
    ports:
      - "4200:80"

  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy

  influxdb:
    image: influxdb:1.8
    ports: ["8086:8086"]
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: k6db

  grafana:
    image: grafana/grafana:10.2.3
    ports: ["3001:3000"]
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  k6:
    image: grafana/k6
    volumes:
      - ./loadtest.js:/scripts/loadtest.js
    entrypoint:
      - k6
      - run
      - --out
      - influxdb=http://influxdb:8086/k6db
      - /scripts/loadtest.js
    depends_on:
      - lb
      - influxdb
    networks:
      - default

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345" # host:container

volumes:
  db-data:
  influx-data:
  grafana-data:
  loki-data:
