name: CI & Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: focusboard
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ── Test & Build API ────────────────────────────────────────────────
      - name: Setup Node.js for API
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: focusboard-api/package-lock.json
      - name: Install & Test API
        working-directory: focusboard-api
        run: |
          npm ci
          npm test
      - name: Build API Docker image
        run: |
          docker build \
            --file focusboard-api/Dockerfile \
            --tag focusboard-api:ci-build \
            focusboard-api

      # ── Test & Build UI ─────────────────────────────────────────────────
      - name: Setup Node.js for UI
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: focusboard-ui/package-lock.json

      - name: Install Chromium for headless tests
        run: sudo apt-get update && sudo apt-get install -y chromium-browser
      - name: Install & Test UI
        working-directory: focusboard-ui
        run: |
          npm ci
          npm test -- --browsers=ChromeHeadless --watch=false
      - name: Build UI Docker image
        run: |
          docker build \
            --file focusboard-ui/Dockerfile \
            --tag focusboard-ui:ci-build \
            focusboard-ui

  e2e:
    needs: test-and-build
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: focusboard
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: [5432:5432]
      api:
        image: focusboard-api:ci-build
        env:
          DATABASE_URL: postgres://postgres@db:5432/focusboard
        ports: [3000:3000]
      ui:
        image: focusboard-ui:ci-build
        ports: [4200:80]

    steps:
      - uses: actions/checkout@v4

      - name: Wait for DB
        run: |
          until docker run --network host postgres:16 pg_isready -h localhost -p 5432; do
            sleep 1
          done

      - name: Wait for API
        run: |
          n=0
          until curl -sSf http://localhost:3000/health || [ $n -gt 20 ]; do
            ((n++)); sleep 1
          done

      - name: Wait for UI
        run: |
          n=0
          until curl -sSf http://localhost:4200 || [ $n -gt 20 ]; do
            ((n++)); sleep 1
          done

      - name: Run Cypress E2E
        working-directory: focusboard-ui
        run: |
          npm ci
          npx cypress run --browser chrome --headless
